version: '3.4'

services:
  db-identity:
    image: sql-server-identity:latest
    environment:
      - ACCEPT_EULA=Y      
      - SA_PASSWORD=Amarelo*01
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - 1433:1433
